import XCTest
@testable import starsky

// Fake FilePicking that returns a pre-defined URL or nil
final class FakePicker: FilePicking {
    let result: URL?
    init(result: URL?) { self.result = result }
    func pickFolder(completion: @escaping (URL?) -> Void) {
        // Call completion asynchronously on main queue to mimic NSOpenPanel behavior
        DispatchQueue.main.async {
            completion(self.result)
        }
    }
}

// Fake web view evaluator to capture JS evaluation
final class FakeWebView: WebViewEvaluating {
    var lastJS: String? = nil
    var onEvaluate: ((String) -> Void)?
    func evaluateJavaScript(_ javaScriptString: String, completionHandler: ((Any?, Error?) -> Void)?) {
        lastJS = javaScriptString
        onEvaluate?(javaScriptString)
        completionHandler?(nil, nil)
    }
}

final class FilePickerControllerTests: XCTestCase {
    // Helper to parse JS arguments produced by jsForURL
    private func parseJSArgs(_ js: String) throws -> [Any] {
        guard let open = js.firstIndex(of: "("), let close = js.lastIndex(of: ")") else {
            throw NSError(domain: "ParseError", code: 1)
        }
        let inside = js[js.index(after: open)...js.index(before: close)]
        let arrayString = "[" + inside + "]"
        guard let data = arrayString.data(using: .utf8) else { throw NSError(domain: "ParseError", code: 2) }
        let obj = try JSONSerialization.jsonObject(with: data, options: [])
        guard let arr = obj as? [Any] else { throw NSError(domain: "ParseError", code: 3) }
        return arr
    }

    func testPerformPickReturnsPath() throws {
        // Create a temporary directory so bookmark creation succeeds
        let tempDir = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
        try FileManager.default.createDirectory(at: tempDir, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: tempDir) }

        let expectedURL = tempDir
        let fake = FakePicker(result: expectedURL)
        let controller = FilePickerController(picker: fake)
        let fakeWeb = FakeWebView()

        let expect = expectation(description: "js evaluated")
        fakeWeb.onEvaluate = { js in
            expect.fulfill()
        }

        controller.performPick(webView: fakeWeb, requestId: <#String#>)

        wait(for: [expect], timeout: 1.0)

        // Debug print
        print("DEBUG fakeWeb.lastJS=\(String(describing: fakeWeb.lastJS))")

        // Expect JS string generated by the controller
        guard let js = fakeWeb.lastJS else { XCTFail("no JS evaluated"); return }

        let args = try parseJSArgs(js)
        // First arg is the path string
        XCTAssertEqual(args.count, 2)
        if let path = args[0] as? String {
            XCTAssertEqual(path, expectedURL.path)
        } else {
            XCTFail("first arg is not a string")
        }

        // Second arg should be a base64 string that decodes to Data
        if let bookmark = args[1] as? String {
            let data = Data(base64Encoded: bookmark)
            XCTAssertNotNil(data)
            XCTAssertFalse(data!.isEmpty)
        } else {
            XCTFail("bookmark is null or not a string")
        }
    }

    func testPerformPickReturnsNullOnCancel() throws {
        let fake = FakePicker(result: nil)
        let controller = FilePickerController(picker: fake)
        let fakeWeb = FakeWebView()

        let expect = expectation(description: "js evaluated")
        fakeWeb.onEvaluate = { js in
            expect.fulfill()
        }

        controller.performPick(webView: fakeWeb)

        wait(for: [expect], timeout: 1.0)

        guard let js = fakeWeb.lastJS else { XCTFail("no JS evaluated"); return }
        let args = try parseJSArgs(js)
        XCTAssertEqual(args.count, 2)
        // expect both nulls
        XCTAssertTrue(args[0] is NSNull)
        XCTAssertTrue(args[1] is NSNull)
    }

    func testPerformPickHandlesWebViewNil() throws {
        let fake = FakePicker(result: URL(fileURLWithPath: "/tmp/x"))
        let controller = FilePickerController(picker: fake)

        // Should not throw when webView is nil
        controller.performPick(webView: nil)
    }

    // New unit tests that exercise jsForURL edge cases directly
    func testJsForURLEscapesSingleQuote() throws {
        let path = "/tmp/some/fi'le"
        let url = URL(fileURLWithPath: path)
        let js = FilePickerController.jsForURL(url)
        // Should produce a JS call with a valid JSON string or a safely escaped single-quoted string
        XCTAssertTrue(js.contains("onFolderSelected("))
        XCTAssertTrue(js.hasSuffix(")"))
        // Evaluate that the JS contains either a quoted JSON string or escaped single quote
        XCTAssertTrue(js.contains("\\'") || js.contains("\"") )
    }

    func testJsForURLHandlesDoubleQuotesAndUnicode() throws {
        let path = "/tmp/quote\"and_unicode_✓"
        let url = URL(fileURLWithPath: path)
        let js = FilePickerController.jsForURL(url)
        XCTAssertTrue(js.contains("onFolderSelected("))
        XCTAssertTrue(js.hasSuffix(")"))
        // When encoded as JSON it should contain the escaped double-quote sequence or unicode preserved
        XCTAssertTrue(js.contains("\\\"") || js.contains("✓"))
    }

    func testJsForURLHandlesEmptyString() throws {
        let path = ""
        let url = URL(fileURLWithPath: path)
        let js = FilePickerController.jsForURL(url)
        XCTAssertTrue(js.contains("onFolderSelected("))
        XCTAssertTrue(js.hasSuffix(")"))
    }

    func testJsForURLNilProducesNulls() throws {
        let js = FilePickerController.jsForURL(nil)
        XCTAssertEqual(js, "window.onFolderSelected(null, null)")
    }

    func testJsForURLProducesBookmarkForExistingFolder() throws {
        // create temp dir
        let tempDir = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
        try FileManager.default.createDirectory(at: tempDir, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: tempDir) }

        let js = FilePickerController.jsForURL(tempDir)
        let args = try parseJSArgs(js)
        XCTAssertEqual(args.count, 2)
        // path should match
        XCTAssertEqual(args[0] as? String, tempDir.path)
        // bookmark should be decodable base64
        if let bookmark = args[1] as? String {
            let data = Data(base64Encoded: bookmark)
            XCTAssertNotNil(data)
            XCTAssertFalse(data!.isEmpty)
        } else {
            XCTFail("bookmark is null or not a string")
        }
    }
}
