import XCTest
@testable import starsky

// Fake FilePicking that returns a pre-defined path or nil
final class FakePicker: FilePicking {
    let result: String?
    init(result: String?) { self.result = result }
    func pickFolder(completion: @escaping (String?) -> Void) {
        // Call completion asynchronously on main queue to mimic NSOpenPanel behavior
        DispatchQueue.main.async {
            completion(self.result)
        }
    }
}

// Fake web view evaluator to capture JS evaluation
final class FakeWebView: WebViewEvaluating {
    var lastJS: String? = nil
    var onEvaluate: ((String) -> Void)?
    func evaluateJavaScript(_ javaScriptString: String, completionHandler: ((Any?, Error?) -> Void)?) {
        lastJS = javaScriptString
        onEvaluate?(javaScriptString)
        completionHandler?(nil, nil)
    }
}

final class FilePickerControllerTests: XCTestCase {
    func testPerformPickReturnsPath() throws {
        let expectedPath = "/tmp/some/folder"
        let fake = FakePicker(result: expectedPath)
        let controller = FilePickerController(picker: fake)
        let fakeWeb = FakeWebView()

        let expect = expectation(description: "js evaluated")
        fakeWeb.onEvaluate = { js in
            expect.fulfill()
        }

        controller.performPick(webView: fakeWeb)

        wait(for: [expect], timeout: 1.0)

        // Debug print
        print("DEBUG fakeWeb.lastJS=\(String(describing: fakeWeb.lastJS))")

        // Expect exact JS string generated by the controller
        let expectedJS = FilePickerController.jsForPath(expectedPath)
        XCTAssertEqual(fakeWeb.lastJS, expectedJS)
    }

    func testPerformPickReturnsNullOnCancel() throws {
        let fake = FakePicker(result: nil)
        let controller = FilePickerController(picker: fake)
        let fakeWeb = FakeWebView()

        let expect = expectation(description: "js evaluated")
        fakeWeb.onEvaluate = { js in
            expect.fulfill()
        }

        controller.performPick(webView: fakeWeb)

        wait(for: [expect], timeout: 1.0)

        XCTAssertEqual(fakeWeb.lastJS, FilePickerController.jsForPath(nil))
    }

    func testPerformPickHandlesWebViewNil() throws {
        let fake = FakePicker(result: "/tmp/x")
        let controller = FilePickerController(picker: fake)

        // Should not throw when webView is nil
        controller.performPick(webView: nil)
    }
}
