version: "2"
exclude_patterns:
  - "starsky/starsky.foundation.database/Migrations/"
  - "starsky/starskytest/"
  - "**/*.spec.ts"
  - "**/*.spec.tsx"
  - "**/*.stories.tsx"
  - "**/*.d.ts"
  - "**/dist/"

checks:
  argument-count:
    enabled: true
    config:
      threshold: 7
  complex-logic:
    enabled: true
    config:
      threshold: 7
  file-lines:
    enabled: false
    config:
      threshold: 1500
  method-complexity:
    enabled: true
    config:
      threshold: 15
  method-count:
    enabled: true
  method-lines:
    enabled: false
  nested-control-flow:
    enabled: true
  return-statements:
    enabled: false
  similar-code:
    enabled: false
  identical-code:
    enabled: true
