#!/bin/bash
DATE=`date '+%Y-%m-%d %H:%M:%S'`

cd "$(dirname "$0")"

dotnet test --list-tests | awk '{ if ( NR > 8  ) { print } }' > listoftests.bak

(echo " [< starsky/starskyTests docs](readme.md) " ; echo -e "\n# Starsky Tests List of Tests \n \n This is an autogenerated list of all Unitests \n To update this file use: \n \`\`\`\nbash ./readme-listoftests-update.sh \n\`\`\` " ; echo "Last updated: " $DATE ; echo  "\`\`\`" ; cat listoftests.bak ; echo "\`\`\`" ) > readme-listoftests.md
rm listoftests.bak
