sonar.issue.ignore.multicriteria=e1,e2

sonar.issue.ignore.multicriteria.e1.ruleKey=swift:S1075
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.swift

sonar.issue.ignore.multicriteria.e2.ruleKey=swift:S7485
sonar.issue.ignore.multicriteria.e2.resourceKey=**/MainWindowController.swift

sonar.issue.ignore.multicriteria.e3.ruleKey=swift:S4507
sonar.issue.ignore.multicriteria.e3.resourceKey=**/MainWindowController.swift

sonar.coverage.exclusions=**/AppDelegate.swift
