name: 'Use Dotnet core version'
description: 'Use Dotnet core version'
runs:
  using: "composite"
  steps:
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.404
