// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: trace.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace OpenTelemetry.Proto.Trace.V1
{

    [global::ProtoBuf.ProtoContract()]
    public partial class TracesData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"resource_spans")]
        public global::System.Collections.Generic.List<ResourceSpans> ResourceSpans { get; } = new global::System.Collections.Generic.List<ResourceSpans>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ResourceSpans : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"resource")]
        public global::OpenTelemetry.Proto.Resource.V1.Resource Resource { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"scope_spans")]
        public global::System.Collections.Generic.List<ScopeSpans> ScopeSpans { get; } = new global::System.Collections.Generic.List<ScopeSpans>();

        [global::ProtoBuf.ProtoMember(3, Name = @"schema_url")]
        [global::System.ComponentModel.DefaultValue("")]
        public string SchemaUrl { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ScopeSpans : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"scope")]
        public global::OpenTelemetry.Proto.Common.V1.InstrumentationScope Scope { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"spans")]
        public global::System.Collections.Generic.List<Span> Spans { get; } = new global::System.Collections.Generic.List<Span>();

        [global::ProtoBuf.ProtoMember(3, Name = @"schema_url")]
        [global::System.ComponentModel.DefaultValue("")]
        public string SchemaUrl { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Span : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"trace_id")]
        public byte[] TraceId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"span_id")]
        public byte[] SpanId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"trace_state")]
        [global::System.ComponentModel.DefaultValue("")]
        public string TraceState { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"parent_span_id")]
        public byte[] ParentSpanId { get; set; }

        [global::ProtoBuf.ProtoMember(16, Name = @"flags", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public uint Flags { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(6, Name = @"kind")]
        public SpanKind Kind { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"start_time_unix_nano", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong StartTimeUnixNano { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"end_time_unix_nano", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong EndTimeUnixNano { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"attributes")]
        public global::System.Collections.Generic.List<global::OpenTelemetry.Proto.Common.V1.KeyValue> Attributes { get; } = new global::System.Collections.Generic.List<global::OpenTelemetry.Proto.Common.V1.KeyValue>();

        [global::ProtoBuf.ProtoMember(10, Name = @"dropped_attributes_count")]
        public uint DroppedAttributesCount { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"events")]
        public global::System.Collections.Generic.List<Event> Events { get; } = new global::System.Collections.Generic.List<Event>();

        [global::ProtoBuf.ProtoMember(12, Name = @"dropped_events_count")]
        public uint DroppedEventsCount { get; set; }

        [global::ProtoBuf.ProtoMember(13, Name = @"links")]
        public global::System.Collections.Generic.List<Link> Links { get; } = new global::System.Collections.Generic.List<Link>();

        [global::ProtoBuf.ProtoMember(14, Name = @"dropped_links_count")]
        public uint DroppedLinksCount { get; set; }

        [global::ProtoBuf.ProtoMember(15, Name = @"status")]
        public Status Status { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class Event : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"time_unix_nano", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
            public ulong TimeUnixNano { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"name")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Name { get; set; } = "";

            [global::ProtoBuf.ProtoMember(3, Name = @"attributes")]
            public global::System.Collections.Generic.List<global::OpenTelemetry.Proto.Common.V1.KeyValue> Attributes { get; } = new global::System.Collections.Generic.List<global::OpenTelemetry.Proto.Common.V1.KeyValue>();

            [global::ProtoBuf.ProtoMember(4, Name = @"dropped_attributes_count")]
            public uint DroppedAttributesCount { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class Link : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"trace_id")]
            public byte[] TraceId { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"span_id")]
            public byte[] SpanId { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"trace_state")]
            [global::System.ComponentModel.DefaultValue("")]
            public string TraceState { get; set; } = "";

            [global::ProtoBuf.ProtoMember(4, Name = @"attributes")]
            public global::System.Collections.Generic.List<global::OpenTelemetry.Proto.Common.V1.KeyValue> Attributes { get; } = new global::System.Collections.Generic.List<global::OpenTelemetry.Proto.Common.V1.KeyValue>();

            [global::ProtoBuf.ProtoMember(5, Name = @"dropped_attributes_count")]
            public uint DroppedAttributesCount { get; set; }

            [global::ProtoBuf.ProtoMember(6, Name = @"flags", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
            public uint Flags { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public enum SpanKind
        {
            [global::ProtoBuf.ProtoEnum(Name = @"SPAN_KIND_UNSPECIFIED")]
            SpanKindUnspecified = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"SPAN_KIND_INTERNAL")]
            SpanKindInternal = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"SPAN_KIND_SERVER")]
            SpanKindServer = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"SPAN_KIND_CLIENT")]
            SpanKindClient = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"SPAN_KIND_PRODUCER")]
            SpanKindProducer = 4,
            [global::ProtoBuf.ProtoEnum(Name = @"SPAN_KIND_CONSUMER")]
            SpanKindConsumer = 5,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Status : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(2, Name = @"message")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Message { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"code")]
        public StatusCode Code { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum StatusCode
        {
            [global::ProtoBuf.ProtoEnum(Name = @"STATUS_CODE_UNSET")]
            StatusCodeUnset = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"STATUS_CODE_OK")]
            StatusCodeOk = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"STATUS_CODE_ERROR")]
            StatusCodeError = 2,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum SpanFlags
    {
        [global::ProtoBuf.ProtoEnum(Name = @"SPAN_FLAGS_DO_NOT_USE")]
        SpanFlagsDoNotUse = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"SPAN_FLAGS_TRACE_FLAGS_MASK")]
        SpanFlagsTraceFlagsMask = 255,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
