//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace starsky.feature.language {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LanguageContent {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageContent() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("starsky.feature.language.LanguageContent", typeof(LanguageContent).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string MessageMoveFolderIntoTrashIntroText {
            get {
                return ResourceManager.GetString("MessageMoveFolderIntoTrashIntroText", resourceCulture);
            }
        }
        
        internal static string MessageCancel {
            get {
                return ResourceManager.GetString("MessageCancel", resourceCulture);
            }
        }
        
        internal static string MessageTrash {
            get {
                return ResourceManager.GetString("MessageTrash", resourceCulture);
            }
        }
        
        internal static string MessageMoveToTrash {
            get {
                return ResourceManager.GetString("MessageMoveToTrash", resourceCulture);
            }
        }
        
        internal static string MessageMoveCurrentFolderToTrash {
            get {
                return ResourceManager.GetString("MessageMoveCurrentFolderToTrash", resourceCulture);
            }
        }
        
        internal static string MessageMove {
            get {
                return ResourceManager.GetString("MessageMove", resourceCulture);
            }
        }
        
        internal static string MessageTo {
            get {
                return ResourceManager.GetString("MessageTo", resourceCulture);
            }
        }
        
        internal static string MessageRestoreFromTrash {
            get {
                return ResourceManager.GetString("MessageRestoreFromTrash", resourceCulture);
            }
        }
        
        internal static string MessageSynchronizeManually {
            get {
                return ResourceManager.GetString("MessageSynchronizeManually", resourceCulture);
            }
        }
        
        internal static string MessageDownload {
            get {
                return ResourceManager.GetString("MessageDownload", resourceCulture);
            }
        }
        
        internal static string MessagePublish {
            get {
                return ResourceManager.GetString("MessagePublish", resourceCulture);
            }
        }
        
        internal static string MessageReadOnlyFile {
            get {
                return ResourceManager.GetString("MessageReadOnlyFile", resourceCulture);
            }
        }
        
        internal static string MessageNotFoundSourceMissing {
            get {
                return ResourceManager.GetString("MessageNotFoundSourceMissing", resourceCulture);
            }
        }
        
        internal static string MessageServerInputError {
            get {
                return ResourceManager.GetString("MessageServerInputError", resourceCulture);
            }
        }
        
        internal static string MessageIsInTheTrash {
            get {
                return ResourceManager.GetString("MessageIsInTheTrash", resourceCulture);
            }
        }
        
        internal static string MessageDeletedRestoreInstruction {
            get {
                return ResourceManager.GetString("MessageDeletedRestoreInstruction", resourceCulture);
            }
        }
        
        internal static string MessageHome {
            get {
                return ResourceManager.GetString("MessageHome", resourceCulture);
            }
        }
        
        internal static string MessagePhotosOfThisWeek {
            get {
                return ResourceManager.GetString("MessagePhotosOfThisWeek", resourceCulture);
            }
        }
        
        internal static string MessageImport {
            get {
                return ResourceManager.GetString("MessageImport", resourceCulture);
            }
        }
        
        internal static string MessagePreferences {
            get {
                return ResourceManager.GetString("MessagePreferences", resourceCulture);
            }
        }
        
        internal static string MessageLogout {
            get {
                return ResourceManager.GetString("MessageLogout", resourceCulture);
            }
        }
        
        internal static string MessageSaved {
            get {
                return ResourceManager.GetString("MessageSaved", resourceCulture);
            }
        }
        
        internal static string MessageImportHeader {
            get {
                return ResourceManager.GetString("MessageImportHeader", resourceCulture);
            }
        }
        
        internal static string MessageCloseDetailScreenDialog {
            get {
                return ResourceManager.GetString("MessageCloseDetailScreenDialog", resourceCulture);
            }
        }
        
        internal static string MessageCloseDialogBackToFolder {
            get {
                return ResourceManager.GetString("MessageCloseDialogBackToFolder", resourceCulture);
            }
        }
        
        internal static string MessageIncludingColonWord {
            get {
                return ResourceManager.GetString("MessageIncludingColonWord", resourceCulture);
            }
        }
        
        internal static string MessageAddLocation {
            get {
                return ResourceManager.GetString("MessageAddLocation", resourceCulture);
            }
        }
        
        internal static string MessageUpdateLocation {
            get {
                return ResourceManager.GetString("MessageUpdateLocation", resourceCulture);
            }
        }
        
        internal static string MessageViewLocation {
            get {
                return ResourceManager.GetString("MessageViewLocation", resourceCulture);
            }
        }
        
        internal static string MessageErrorGenericFail {
            get {
                return ResourceManager.GetString("MessageErrorGenericFail", resourceCulture);
            }
        }
        
        internal static string MessageNoPhotosInFolder {
            get {
                return ResourceManager.GetString("MessageNoPhotosInFolder", resourceCulture);
            }
        }
        
        internal static string MessageNewUserNoPhotosInFolder {
            get {
                return ResourceManager.GetString("MessageNewUserNoPhotosInFolder", resourceCulture);
            }
        }
        
        internal static string MessageItemsOutsideFilter {
            get {
                return ResourceManager.GetString("MessageItemsOutsideFilter", resourceCulture);
            }
        }
        
        internal static string MessageSelectPresentPerfect {
            get {
                return ResourceManager.GetString("MessageSelectPresentPerfect", resourceCulture);
            }
        }
        
        internal static string MessageSelectAction {
            get {
                return ResourceManager.GetString("MessageSelectAction", resourceCulture);
            }
        }
        
        internal static string MessageNoneSelected {
            get {
                return ResourceManager.GetString("MessageNoneSelected", resourceCulture);
            }
        }
        
        internal static string MessageUndoSelection {
            get {
                return ResourceManager.GetString("MessageUndoSelection", resourceCulture);
            }
        }
        
        internal static string MessageSelectAll {
            get {
                return ResourceManager.GetString("MessageSelectAll", resourceCulture);
            }
        }
        
        internal static string MessageAllName {
            get {
                return ResourceManager.GetString("MessageAllName", resourceCulture);
            }
        }
        
        internal static string MessageSelectFurther {
            get {
                return ResourceManager.GetString("MessageSelectFurther", resourceCulture);
            }
        }
        
        internal static string MessageGoToParentFolder {
            get {
                return ResourceManager.GetString("MessageGoToParentFolder", resourceCulture);
            }
        }
        
        internal static string MessageMkdir {
            get {
                return ResourceManager.GetString("MessageMkdir", resourceCulture);
            }
        }
        
        internal static string MessageRenameDir {
            get {
                return ResourceManager.GetString("MessageRenameDir", resourceCulture);
            }
        }
        
        internal static string MessageLabels {
            get {
                return ResourceManager.GetString("MessageLabels", resourceCulture);
            }
        }
        
        internal static string MessageRenameFileName {
            get {
                return ResourceManager.GetString("MessageRenameFileName", resourceCulture);
            }
        }
        
        internal static string MessageRotateToRight {
            get {
                return ResourceManager.GetString("MessageRotateToRight", resourceCulture);
            }
        }
        
        internal static string MessageDeleteImmediately {
            get {
                return ResourceManager.GetString("MessageDeleteImmediately", resourceCulture);
            }
        }
        
        internal static string MessageVideoPlayBackError {
            get {
                return ResourceManager.GetString("MessageVideoPlayBackError", resourceCulture);
            }
        }
        
        internal static string MessageVideoNotFound {
            get {
                return ResourceManager.GetString("MessageVideoNotFound", resourceCulture);
            }
        }
        
        internal static string MessageColorClassIsUpdated {
            get {
                return ResourceManager.GetString("MessageColorClassIsUpdated", resourceCulture);
            }
        }
        
        internal static string ColorClassColour0 {
            get {
                return ResourceManager.GetString("ColorClassColour0", resourceCulture);
            }
        }
        
        internal static string ColorClassColour1 {
            get {
                return ResourceManager.GetString("ColorClassColour1", resourceCulture);
            }
        }
        
        internal static string ColorClassColour2 {
            get {
                return ResourceManager.GetString("ColorClassColour2", resourceCulture);
            }
        }
        
        internal static string ColorClassColour3 {
            get {
                return ResourceManager.GetString("ColorClassColour3", resourceCulture);
            }
        }
        
        internal static string ColorClassColour4 {
            get {
                return ResourceManager.GetString("ColorClassColour4", resourceCulture);
            }
        }
        
        internal static string ColorClassColour5 {
            get {
                return ResourceManager.GetString("ColorClassColour5", resourceCulture);
            }
        }
        
        internal static string ColorClassColour6 {
            get {
                return ResourceManager.GetString("ColorClassColour6", resourceCulture);
            }
        }
        
        internal static string ColorClassColour7 {
            get {
                return ResourceManager.GetString("ColorClassColour7", resourceCulture);
            }
        }
        
        internal static string ColorClassColour8 {
            get {
                return ResourceManager.GetString("ColorClassColour8", resourceCulture);
            }
        }
        
        internal static string ColorClassColourResetFilter {
            get {
                return ResourceManager.GetString("ColorClassColourResetFilter", resourceCulture);
            }
        }
        
        internal static string MessageCloseDialog {
            get {
                return ResourceManager.GetString("MessageCloseDialog", resourceCulture);
            }
        }
        
        internal static string MessageDesktopEditorOpenSingleFile {
            get {
                return ResourceManager.GetString("MessageDesktopEditorOpenSingleFile", resourceCulture);
            }
        }
        
        internal static string MessageDesktopEditorOpenMultipleFiles {
            get {
                return ResourceManager.GetString("MessageDesktopEditorOpenMultipleFiles", resourceCulture);
            }
        }
        
        internal static string MessageDesktopEditorUnableToOpen {
            get {
                return ResourceManager.GetString("MessageDesktopEditorUnableToOpen", resourceCulture);
            }
        }
        
        internal static string MessageDesktopEditorConfirmationHeading {
            get {
                return ResourceManager.GetString("MessageDesktopEditorConfirmationHeading", resourceCulture);
            }
        }
        
        internal static string MessageDesktopEditorConfirmationIntroText {
            get {
                return ResourceManager.GetString("MessageDesktopEditorConfirmationIntroText", resourceCulture);
            }
        }
        
        internal static string MessageItemSelectionRequired {
            get {
                return ResourceManager.GetString("MessageItemSelectionRequired", resourceCulture);
            }
        }
        
        internal static string MessageAppSettingsEntireAppScope {
            get {
                return ResourceManager.GetString("MessageAppSettingsEntireAppScope", resourceCulture);
            }
        }
        
        internal static string MessageChangeNeedReSync {
            get {
                return ResourceManager.GetString("MessageChangeNeedReSync", resourceCulture);
            }
        }
        
        internal static string MessageAppSettingsStorageFolder {
            get {
                return ResourceManager.GetString("MessageAppSettingsStorageFolder", resourceCulture);
            }
        }
        
        internal static string MessageAppSettingStorageFolderSaveFail {
            get {
                return ResourceManager.GetString("MessageAppSettingStorageFolderSaveFail", resourceCulture);
            }
        }
        
        internal static string MessageAppSettingStorageFolderEnvUsedFail {
            get {
                return ResourceManager.GetString("MessageAppSettingStorageFolderEnvUsedFail", resourceCulture);
            }
        }
        
        internal static string MessageSwitchButtonDesktopCollectionsRawOn {
            get {
                return ResourceManager.GetString("MessageSwitchButtonDesktopCollectionsRawOn", resourceCulture);
            }
        }
        
        internal static string MessageSwitchButtonDesktopCollectionsJpegDefaultOff {
            get {
                return ResourceManager.GetString("MessageSwitchButtonDesktopCollectionsJpegDefaultOff", resourceCulture);
            }
        }
        
        internal static string MessageSwitchButtonDesktopApplication {
            get {
                return ResourceManager.GetString("MessageSwitchButtonDesktopApplication", resourceCulture);
            }
        }
        
        internal static string MessageSwitchButtonDesktopApplicationDescription {
            get {
                return ResourceManager.GetString("MessageSwitchButtonDesktopApplicationDescription", resourceCulture);
            }
        }
        
        internal static string MessageAppSettingDefaultEditorPhotos {
            get {
                return ResourceManager.GetString("MessageAppSettingDefaultEditorPhotos", resourceCulture);
            }
        }
        
        internal static string MessageAppSettingDefaultEditorPhotosDescription {
            get {
                return ResourceManager.GetString("MessageAppSettingDefaultEditorPhotosDescription", resourceCulture);
            }
        }
        
        internal static string MessageSwitchButtonDesktopCollectionsUpdateError {
            get {
                return ResourceManager.GetString("MessageSwitchButtonDesktopCollectionsUpdateError", resourceCulture);
            }
        }
        
        internal static string MessageSwitchButtonDesktopCollectionsUpdateSuccess {
            get {
                return ResourceManager.GetString("MessageSwitchButtonDesktopCollectionsUpdateSuccess", resourceCulture);
            }
        }
        
        internal static string MessageSwitchButtonDesktopCollectionsRawJpegUpdateError {
            get {
                return ResourceManager.GetString("MessageSwitchButtonDesktopCollectionsRawJpegUpdateError", resourceCulture);
            }
        }
        
        internal static string MessageSwitchButtonDesktopCollectionsRawJpegUpdateSuccess {
            get {
                return ResourceManager.GetString("MessageSwitchButtonDesktopCollectionsRawJpegUpdateSuccess", resourceCulture);
            }
        }
        
        internal static string MessageUnknownUsername {
            get {
                return ResourceManager.GetString("MessageUnknownUsername", resourceCulture);
            }
        }
        
        internal static string MessageDesktopMailLocalhostUsername {
            get {
                return ResourceManager.GetString("MessageDesktopMailLocalhostUsername", resourceCulture);
            }
        }
        
        internal static string MessageUsername {
            get {
                return ResourceManager.GetString("MessageUsername", resourceCulture);
            }
        }
        
        internal static string MessageRole {
            get {
                return ResourceManager.GetString("MessageRole", resourceCulture);
            }
        }
        
        internal static string MessageExamplePassword {
            get {
                return ResourceManager.GetString("MessageExamplePassword", resourceCulture);
            }
        }
        
        internal static string MessageCurrentPassword {
            get {
                return ResourceManager.GetString("MessageCurrentPassword", resourceCulture);
            }
        }
        
        internal static string MessageChangedPassword {
            get {
                return ResourceManager.GetString("MessageChangedPassword", resourceCulture);
            }
        }
        
        internal static string MessageChangedConfirmPassword {
            get {
                return ResourceManager.GetString("MessageChangedConfirmPassword", resourceCulture);
            }
        }
        
        internal static string MessageNoPassword {
            get {
                return ResourceManager.GetString("MessageNoPassword", resourceCulture);
            }
        }
        
        internal static string MessagePassword {
            get {
                return ResourceManager.GetString("MessagePassword", resourceCulture);
            }
        }
        
        internal static string MessagePasswordChanged {
            get {
                return ResourceManager.GetString("MessagePasswordChanged", resourceCulture);
            }
        }
        
        internal static string MessagePasswordNoMatch {
            get {
                return ResourceManager.GetString("MessagePasswordNoMatch", resourceCulture);
            }
        }
        
        internal static string MessagePasswordModalError {
            get {
                return ResourceManager.GetString("MessagePasswordModalError", resourceCulture);
            }
        }
        
        internal static string MessageCreateNewAccount {
            get {
                return ResourceManager.GetString("MessageCreateNewAccount", resourceCulture);
            }
        }
        
        internal static string MessageExampleUsername {
            get {
                return ResourceManager.GetString("MessageExampleUsername", resourceCulture);
            }
        }
        
        internal static string MessageConfirmPassword {
            get {
                return ResourceManager.GetString("MessageConfirmPassword", resourceCulture);
            }
        }
        
        internal static string MessageNoUsernamePassword {
            get {
                return ResourceManager.GetString("MessageNoUsernamePassword", resourceCulture);
            }
        }
        
        internal static string MessageWrongFormatEmailAddress {
            get {
                return ResourceManager.GetString("MessageWrongFormatEmailAddress", resourceCulture);
            }
        }
        
        internal static string MessagePasswordToShort {
            get {
                return ResourceManager.GetString("MessagePasswordToShort", resourceCulture);
            }
        }
        
        internal static string MessageRejectedBadRequest {
            get {
                return ResourceManager.GetString("MessageRejectedBadRequest", resourceCulture);
            }
        }
        
        internal static string MessageRegistrationTurnedOff {
            get {
                return ResourceManager.GetString("MessageRegistrationTurnedOff", resourceCulture);
            }
        }
        
        internal static string MessageSignInInstead {
            get {
                return ResourceManager.GetString("MessageSignInInstead", resourceCulture);
            }
        }
        
        internal static string MessageLegalCreateAccountHtml {
            get {
                return ResourceManager.GetString("MessageLegalCreateAccountHtml", resourceCulture);
            }
        }
        
        internal static string MessageFieldMaxLength {
            get {
                return ResourceManager.GetString("MessageFieldMaxLength", resourceCulture);
            }
        }
        
        internal static string MessageWrongUsernamePassword {
            get {
                return ResourceManager.GetString("MessageWrongUsernamePassword", resourceCulture);
            }
        }
        
        internal static string MessageLockedOut {
            get {
                return ResourceManager.GetString("MessageLockedOut", resourceCulture);
            }
        }
        
        internal static string MessageConnection {
            get {
                return ResourceManager.GetString("MessageConnection", resourceCulture);
            }
        }
        
        internal static string MessageDatabaseConnection {
            get {
                return ResourceManager.GetString("MessageDatabaseConnection", resourceCulture);
            }
        }
        
        internal static string LogoutWarning {
            get {
                return ResourceManager.GetString("LogoutWarning", resourceCulture);
            }
        }
        
        internal static string MessageStayLoggedIn {
            get {
                return ResourceManager.GetString("MessageStayLoggedIn", resourceCulture);
            }
        }
        
        internal static string MessageLogin {
            get {
                return ResourceManager.GetString("MessageLogin", resourceCulture);
            }
        }
        
        internal static string MessageCreateAccount {
            get {
                return ResourceManager.GetString("MessageCreateAccount", resourceCulture);
            }
        }
        
        internal static string MessageMore {
            get {
                return ResourceManager.GetString("MessageMore", resourceCulture);
            }
        }
        
        internal static string MessagePrevious {
            get {
                return ResourceManager.GetString("MessagePrevious", resourceCulture);
            }
        }
        
        internal static string MessageNext {
            get {
                return ResourceManager.GetString("MessageNext", resourceCulture);
            }
        }
        
        internal static string MessageAddName {
            get {
                return ResourceManager.GetString("MessageAddName", resourceCulture);
            }
        }
        
        internal static string MessageTagsWithColon {
            get {
                return ResourceManager.GetString("MessageTagsWithColon", resourceCulture);
            }
        }
        
        internal static string MessageInfoWithColon {
            get {
                return ResourceManager.GetString("MessageInfoWithColon", resourceCulture);
            }
        }
        
        internal static string MessageTagsDescription {
            get {
                return ResourceManager.GetString("MessageTagsDescription", resourceCulture);
            }
        }
        
        internal static string MessageTitleWithColon {
            get {
                return ResourceManager.GetString("MessageTitleWithColon", resourceCulture);
            }
        }
        
        internal static string MessageOverwriteName {
            get {
                return ResourceManager.GetString("MessageOverwriteName", resourceCulture);
            }
        }
        
        internal static string MessageTitleName {
            get {
                return ResourceManager.GetString("MessageTitleName", resourceCulture);
            }
        }
        
        internal static string MessageInfoName {
            get {
                return ResourceManager.GetString("MessageInfoName", resourceCulture);
            }
        }
        
        internal static string MessageWriteErrorReadOnly {
            get {
                return ResourceManager.GetString("MessageWriteErrorReadOnly", resourceCulture);
            }
        }
        
        internal static string MessageErrorNotFoundSourceMissingRunSync {
            get {
                return ResourceManager.GetString("MessageErrorNotFoundSourceMissingRunSync", resourceCulture);
            }
        }
        
        internal static string MessageSearchAndReplaceNameLong {
            get {
                return ResourceManager.GetString("MessageSearchAndReplaceNameLong", resourceCulture);
            }
        }
        
        internal static string MessageSearchAndReplaceNameShort {
            get {
                return ResourceManager.GetString("MessageSearchAndReplaceNameShort", resourceCulture);
            }
        }
        
        internal static string MessageModifyName {
            get {
                return ResourceManager.GetString("MessageModifyName", resourceCulture);
            }
        }
        
        internal static string MessageForceSyncCurrentFolder {
            get {
                return ResourceManager.GetString("MessageForceSyncCurrentFolder", resourceCulture);
            }
        }
        
        internal static string MessageWhereToFindReleaseReleasesUrlTokenHtml {
            get {
                return ResourceManager.GetString("MessageWhereToFindReleaseReleasesUrlTokenHtml", resourceCulture);
            }
        }
        
        internal static string MessageWhereToFindReleaseReleasesUrlTokenContent {
            get {
                return ResourceManager.GetString("MessageWhereToFindReleaseReleasesUrlTokenContent", resourceCulture);
            }
        }
        
        internal static string WhereToFindReleaseElectronApp {
            get {
                return ResourceManager.GetString("WhereToFindReleaseElectronApp", resourceCulture);
            }
        }
        
        internal static string MessageNewVersionUpdateToken {
            get {
                return ResourceManager.GetString("MessageNewVersionUpdateToken", resourceCulture);
            }
        }
        
        internal static string MessageHealthStatusCriticalErrorsWithTheFollowingComponents {
            get {
                return ResourceManager.GetString("MessageHealthStatusCriticalErrorsWithTheFollowingComponents", resourceCulture);
            }
        }
        
        internal static string MessageNoPhotos {
            get {
                return ResourceManager.GetString("MessageNoPhotos", resourceCulture);
            }
        }
        
        internal static string MessageFilesAdded {
            get {
                return ResourceManager.GetString("MessageFilesAdded", resourceCulture);
            }
        }
        
        internal static string MessageApplicationException {
            get {
                return ResourceManager.GetString("MessageApplicationException", resourceCulture);
            }
        }
        
        internal static string MessageRefreshPageTryAgain {
            get {
                return ResourceManager.GetString("MessageRefreshPageTryAgain", resourceCulture);
            }
        }
        
        internal static string MessagePublishSelection {
            get {
                return ResourceManager.GetString("MessagePublishSelection", resourceCulture);
            }
        }
        
        internal static string MessageGenericExportFail {
            get {
                return ResourceManager.GetString("MessageGenericExportFail", resourceCulture);
            }
        }
        
        internal static string MessageRetryExportFail {
            get {
                return ResourceManager.GetString("MessageRetryExportFail", resourceCulture);
            }
        }
        
        internal static string MessageExportReady {
            get {
                return ResourceManager.GetString("MessageExportReady", resourceCulture);
            }
        }
        
        internal static string MessageDownloadAsZipArchive {
            get {
                return ResourceManager.GetString("MessageDownloadAsZipArchive", resourceCulture);
            }
        }
        
        internal static string MessageOneMomentPlease {
            get {
                return ResourceManager.GetString("MessageOneMomentPlease", resourceCulture);
            }
        }
        
        internal static string MessageItemName {
            get {
                return ResourceManager.GetString("MessageItemName", resourceCulture);
            }
        }
        
        internal static string MessageItemNameInUse {
            get {
                return ResourceManager.GetString("MessageItemNameInUse", resourceCulture);
            }
        }
        
        internal static string MessagePublishProfileName {
            get {
                return ResourceManager.GetString("MessagePublishProfileName", resourceCulture);
            }
        }
        
        internal static string MessagePublishProfileNamesErrored {
            get {
                return ResourceManager.GetString("MessagePublishProfileNamesErrored", resourceCulture);
            }
        }
        
        internal static string MessageSelectionName {
            get {
                return ResourceManager.GetString("MessageSelectionName", resourceCulture);
            }
        }
        
        internal static string MessageReadOnlyFolder {
            get {
                return ResourceManager.GetString("MessageReadOnlyFolder", resourceCulture);
            }
        }
        
        internal static string MessageUpdateLabels {
            get {
                return ResourceManager.GetString("MessageUpdateLabels", resourceCulture);
            }
        }
        
        internal static string MessageColorClassification {
            get {
                return ResourceManager.GetString("MessageColorClassification", resourceCulture);
            }
        }
        
        internal static string MessageDateTimeAgoEdited {
            get {
                return ResourceManager.GetString("MessageDateTimeAgoEdited", resourceCulture);
            }
        }
        
        internal static string MessageDateLessThan1Minute {
            get {
                return ResourceManager.GetString("MessageDateLessThan1Minute", resourceCulture);
            }
        }
        
        internal static string MessageDateMinutes {
            get {
                return ResourceManager.GetString("MessageDateMinutes", resourceCulture);
            }
        }
        
        internal static string MessageDateHour {
            get {
                return ResourceManager.GetString("MessageDateHour", resourceCulture);
            }
        }
        
        internal static string MessageCopiedLabels {
            get {
                return ResourceManager.GetString("MessageCopiedLabels", resourceCulture);
            }
        }
        
        internal static string MessagePasteLabels {
            get {
                return ResourceManager.GetString("MessagePasteLabels", resourceCulture);
            }
        }
        
        internal static string MessageCreationDate {
            get {
                return ResourceManager.GetString("MessageCreationDate", resourceCulture);
            }
        }
        
        internal static string MessageCreationDateIsAtUnknownTime {
            get {
                return ResourceManager.GetString("MessageCreationDateIsAtUnknownTime", resourceCulture);
            }
        }
        
        internal static string MessageNounNameless {
            get {
                return ResourceManager.GetString("MessageNounNameless", resourceCulture);
            }
        }
        
        internal static string MessageNounNone {
            get {
                return ResourceManager.GetString("MessageNounNone", resourceCulture);
            }
        }
        
        internal static string MessageLocation {
            get {
                return ResourceManager.GetString("MessageLocation", resourceCulture);
            }
        }
        
        internal static string MessageCreateNewFolderFeature {
            get {
                return ResourceManager.GetString("MessageCreateNewFolderFeature", resourceCulture);
            }
        }
        
        internal static string MessageNonValidDirectoryName {
            get {
                return ResourceManager.GetString("MessageNonValidDirectoryName", resourceCulture);
            }
        }
        
        internal static string MessageGeneralMkdirCreateError {
            get {
                return ResourceManager.GetString("MessageGeneralMkdirCreateError", resourceCulture);
            }
        }
        
        internal static string MessageDirectoryExistError {
            get {
                return ResourceManager.GetString("MessageDirectoryExistError", resourceCulture);
            }
        }
        
        internal static string MessageRenameCurrentFolder {
            get {
                return ResourceManager.GetString("MessageRenameCurrentFolder", resourceCulture);
            }
        }
        
        internal static string MessageRemoveCache {
            get {
                return ResourceManager.GetString("MessageRemoveCache", resourceCulture);
            }
        }
        
        internal static string MessageGeoSync {
            get {
                return ResourceManager.GetString("MessageGeoSync", resourceCulture);
            }
        }
        
        internal static string MessageGeoSyncExplainer {
            get {
                return ResourceManager.GetString("MessageGeoSyncExplainer", resourceCulture);
            }
        }
        
        internal static string MessageManualThumbnailSync {
            get {
                return ResourceManager.GetString("MessageManualThumbnailSync", resourceCulture);
            }
        }
        
        internal static string MessageManualThumbnailSyncExplainer {
            get {
                return ResourceManager.GetString("MessageManualThumbnailSyncExplainer", resourceCulture);
            }
        }
        
        internal static string MessageNonValidExtension {
            get {
                return ResourceManager.GetString("MessageNonValidExtension", resourceCulture);
            }
        }
        
        internal static string MessageChangeToDifferentExtension {
            get {
                return ResourceManager.GetString("MessageChangeToDifferentExtension", resourceCulture);
            }
        }
        
        internal static string MessageRenameServerError {
            get {
                return ResourceManager.GetString("MessageRenameServerError", resourceCulture);
            }
        }
        
        internal static string MessageDisplayOptions {
            get {
                return ResourceManager.GetString("MessageDisplayOptions", resourceCulture);
            }
        }
        
        internal static string MessageDisplayOptionsSwitchButtonCollectionsOff {
            get {
                return ResourceManager.GetString("MessageDisplayOptionsSwitchButtonCollectionsOff", resourceCulture);
            }
        }
        
        internal static string MessageDisplayOptionsSwitchButtonCollectionsOn {
            get {
                return ResourceManager.GetString("MessageDisplayOptionsSwitchButtonCollectionsOn", resourceCulture);
            }
        }
        
        internal static string MessageDisplayOptionsSwitchButtonIsSingleItemOff {
            get {
                return ResourceManager.GetString("MessageDisplayOptionsSwitchButtonIsSingleItemOff", resourceCulture);
            }
        }
        
        internal static string MessageDisplayOptionsSwitchButtonIsSingleItemOn {
            get {
                return ResourceManager.GetString("MessageDisplayOptionsSwitchButtonIsSingleItemOn", resourceCulture);
            }
        }
        
        internal static string MessageDisplayOptionsSwitchButtonIsSocketOn {
            get {
                return ResourceManager.GetString("MessageDisplayOptionsSwitchButtonIsSocketOn", resourceCulture);
            }
        }
        
        internal static string MessageDisplayOptionsSwitchButtonIsSocketOff {
            get {
                return ResourceManager.GetString("MessageDisplayOptionsSwitchButtonIsSocketOff", resourceCulture);
            }
        }
        
        internal static string MessageDownloadSelection {
            get {
                return ResourceManager.GetString("MessageDownloadSelection", resourceCulture);
            }
        }
        
        internal static string MessageOriginalFile {
            get {
                return ResourceManager.GetString("MessageOriginalFile", resourceCulture);
            }
        }
        
        internal static string MessageThumbnailFile {
            get {
                return ResourceManager.GetString("MessageThumbnailFile", resourceCulture);
            }
        }
        
        internal static string MessageModalDatetime {
            get {
                return ResourceManager.GetString("MessageModalDatetime", resourceCulture);
            }
        }
        
        internal static string MessageYear {
            get {
                return ResourceManager.GetString("MessageYear", resourceCulture);
            }
        }
        
        internal static string MessageMonth {
            get {
                return ResourceManager.GetString("MessageMonth", resourceCulture);
            }
        }
        
        internal static string MessageDate {
            get {
                return ResourceManager.GetString("MessageDate", resourceCulture);
            }
        }
        
        internal static string MessageTime {
            get {
                return ResourceManager.GetString("MessageTime", resourceCulture);
            }
        }
        
        internal static string MessageErrorDatetime {
            get {
                return ResourceManager.GetString("MessageErrorDatetime", resourceCulture);
            }
        }
        
        internal static string MessageDeleteIntroText {
            get {
                return ResourceManager.GetString("MessageDeleteIntroText", resourceCulture);
            }
        }
        
        internal static string MessageConnectionRealtimeError {
            get {
                return ResourceManager.GetString("MessageConnectionRealtimeError", resourceCulture);
            }
        }
        
        internal static string MessageApplicationFailed {
            get {
                return ResourceManager.GetString("MessageApplicationFailed", resourceCulture);
            }
        }
        
        internal static string MessageNumberOfResults {
            get {
                return ResourceManager.GetString("MessageNumberOfResults", resourceCulture);
            }
        }
        
        internal static string MessageNoResult {
            get {
                return ResourceManager.GetString("MessageNoResult", resourceCulture);
            }
        }
        
        internal static string MessageTryOtherQuery {
            get {
                return ResourceManager.GetString("MessageTryOtherQuery", resourceCulture);
            }
        }
        
        internal static string MessagePageNumberToken {
            get {
                return ResourceManager.GetString("MessagePageNumberToken", resourceCulture);
            }
        }
        
        internal static string MessageEmptyTrash {
            get {
                return ResourceManager.GetString("MessageEmptyTrash", resourceCulture);
            }
        }
        
        internal static string MessageNotFound {
            get {
                return ResourceManager.GetString("MessageNotFound", resourceCulture);
            }
        }
        
        internal static string MessageGoToHome {
            get {
                return ResourceManager.GetString("MessageGoToHome", resourceCulture);
            }
        }
        
        internal static string MessageReadMoreHere {
            get {
                return ResourceManager.GetString("MessageReadMoreHere", resourceCulture);
            }
        }
        
        internal static string temp1 {
            get {
                return ResourceManager.GetString("temp1", resourceCulture);
            }
        }
    }
}
