version: '3.4'

services:

  mariadb:
    image: lscr.io/linuxserver/mariadb
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=Europe/London
      - MYSQL_DATABASE=${MYSQL_DATABASE} #optional
      - MYSQL_USER=${MYSQL_USER} #optional
      - MYSQL_PASSWORD=${MYSQL_PASSWORD} #optional
    volumes:
      - sqldata:/config
    ports:
      - 3306:3306
    restart: unless-stopped
    networks:
      internalnetwork: null

  starsky:
    image: ${DOCKER_REGISTRY-}starsky
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ISDEMO=true
    environment:
      - PORT=${STARSKY_PORT}
      - CI=true
      - app__databaseType=mysql
      - app__IsAccountRegisterOpen=true
      - app__addSwagger=true
      - app__databaseConnection=Server=host.docker.internal;database=${MYSQL_DATABASE};uid=${MYSQL_USER};pwd=${MYSQL_PASSWORD};
    ports:
      - "${STARSKY_PORT}:${STARSKY_PORT}"
    networks:
      internalnetwork: null

networks:
  proxy:
    driver: bridge
  internalnetwork:
    driver: bridge

volumes:
  sqldata:    