version: '3.4'

services:

  mariadb:
    image: lscr.io/linuxserver/mariadb
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=${MARIA_DB_ROOT_PASSWORD}
      - TZ=Europe/London
      - MYSQL_DATABASE=${MYSQL_DATABASE} #optional
      - MYSQL_USER=${MYSQL_USER} #optional
      - MYSQL_PASSWORD=${MYSQL_PASSWORD} #optional
    volumes:
      - sqldata:/config
    ports:
      - "${MARIA_DB_PORT}:3306"
    restart: unless-stopped
    networks:
      internalnetwork: null

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      # https://docs.phpmyadmin.net/en/latest/setup.html#docker-environment-variables
      PMA_HOST: host.docker.internal
      PMA_PORT: ${MARIA_DB_PORT}
      MYSQL_ROOT_PASSWORD: "${MARIA_DB_ROOT_PASSWORD}"
    ports:
      - "${PHP_MY_ADMIN_PORT}:80"

  starsky:
    image: ${DOCKER_REGISTRY-}starsky
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - ghcr.io/qdraw/starsky:master
      args:
        - IS__DEMO=true # arg name is ISDEMO 
        - TEST=false
    environment:
      - PORT=${STARSKY_PORT}
      - app__verbose=true
      - app__databaseType=mysql
      - app__IsAccountRegisterOpen=true
      - app__addSwagger=true
      - app__DemoUnsafeDeleteStorageFolder=false
      - app__useDiskWatcher=false
      - app__storageFolder=/app/pictures
      - DOTNET_USE_POLLING_FILE_WATCHER=true
      - DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE=false
      - app__databaseConnection=Server=host.docker.internal;port=${MARIA_DB_PORT};database=${MYSQL_DATABASE};uid=${MYSQL_USER};pwd=${MYSQL_PASSWORD};
    ports:
      - "${STARSKY_PORT}:${STARSKY_PORT}"
    volumes:
      - "~/Pictures:/app/pictures"
    depends_on:
      - "mariadb"
    networks:
      internalnetwork: null

networks:
  internalnetwork:
    driver: bridge

volumes:
  sqldata:    