<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <CollectCoverage>true</CollectCoverage>
    <CoverletOutputFormat>cobertura</CoverletOutputFormat>
    <CoverletOutput>$(MSBuildProjectDirectory)\TestResults\coverage.xml</CoverletOutput>
    <Threshold>100</Threshold>
    <ThresholdType>line</ThresholdType>
    <ThresholdStat>total</ThresholdStat>
    <Include>[starsky]Starsky.Windows.Models.*,[starsky]Starsky.Windows.Services.BackendApiClient,[starsky]Starsky.Windows.Services.FileWorkspaceService</Include>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.msbuild" Version="6.0.2" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.6.2" />
    <PackageReference Include="MSTest.TestFramework" Version="3.6.2" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="starsky">
      <HintPath>..\bin\Debug\net8.0-windows10.0.19041.0\win-x64\starsky.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
