variables:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  NUGET_XMLDOC_MODE: skip
  CI: true
  npm_config_cache: $(Pipeline.Workspace)/.npm
  NUGET_PACKAGES: $(Pipeline.Workspace)/.nuget/packages
  sonarqube: true

pool:
  vmImage: ubuntu-20.04
  demands:
  - msbuild
  - java

trigger:
  branches:
    include:
    - master
    - release/*
    exclude:
    - feature/*
  paths:
      include:
      - starsky/*
      exclude:
      - starskyapp/*
      - starsky-tools/*
      - starsky.netframework/*
      - starsky/readme.md
      - starsky/starsky/readme.md
      - starsky/starsky/clientapp/readme.md

# specific path build
pr:
  branches:
    exclude:
    - master
  paths:
    include:
    - starsky/*
    exclude:
    - starskyapp/*
    - starsky-tools/*
    - starsky.netframework/*

steps:
  - template: /pipelines/azure/steps/use_dotnet_version.yml

  # - template: /pipelines/azure/steps/use_jdk11_powershell.yml

  - template: /pipelines/azure/steps/build_server.yml
    parameters:
      vstest: true

  - template: /pipelines/azure/steps/build_clientapp.yml

  - task: PublishCodeCoverageResults@1
    displayName: 'Publish code coverage from $(Build.SourcesDirectory)\starsky\starskytest\coverage-merge-cobertura.xml'
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(Build.SourcesDirectory)\starsky\starskytest\coverage-merge-cobertura.xml'

  - task: PublishPipelineArtifact@1
    enabled: true
    displayName: Publish linux-arm Artifact
    inputs:
      targetPath: '$(Build.SourcesDirectory)\starsky\starsky-linux-arm.zip'
      artifact: 'linux-arm'
      publishLocation: "pipeline"

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: linux-arm64'
    inputs:
      PathtoPublish: '$(Build.SourcesDirectory)\starsky\starsky-linux-arm64.zip'
      ArtifactName: 'linux-arm64'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: generic-netcore'
    inputs:
      PathtoPublish: '$(Build.SourcesDirectory)\starsky\starsky-generic-netcore.zip'
      ArtifactName: 'generic-netcore'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: coverage.report zip'
    inputs:
      PathtoPublish: '$(Build.SourcesDirectory)\starsky\starskytest\coverage-report.zip'
      ArtifactName: coverage.report
