trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - documentation
    - starsky/readme.md
    - starsky/starsky/readme.md
    - starsky/starsky/readme-docker-hub.md
    - starsky/starsky/readme-docker-development.md
    - starsky/starsky/clientapp/readme.md
    - starsky/**/readme.md
    - starskydesktop/readme.md
    - starskydesktop/docs-assets/
    - starsky/starskytest/readme.md
    - starsky-tools/readme.md
    - starsky-tools/**/readme.md

pr: none

variables:
  CI: true
  npm_config_cache: $(Pipeline.Workspace)/.npm
  DOCS_SERVER_URL: $(serverUrl) # starts with ftp:// 
              # use: serverUrl, username etc. as variable name is devops
  DOCS_USERNAME: $(username) # ftp user name
  DOCS_PASSWORD: $(password)
  DOCS_URL: $(url) # public url/domain
  DOCS_BASE_URL: $(baseUrl) # dir in domain
  

stages:
- stage: builddocumentation
  displayName: 'Build Documentation'
  jobs:
  - job: builddocumentation
    displayName: 'Build Documentation'
    timeoutInMinutes: 10 # how long to run the job before automatically cancelling
    cancelTimeoutInMinutes: 2 # how much time to give 'run always even if cancelled tasks' before stopping them
    pool:
      vmImage: 'ubuntu-22.04'

    steps:
    - checkout: self
      clean: true
      fetchDepth: 1

    - template: /pipelines/azure/steps/build_documentation.yml
      parameters:
        npmConfigCache: $(npm_config_cache)
        url: $(DOCS_URL)
        baseUrl: $(DOCS_BASE_URL)

    - template: /pipelines/azure/steps/publish_artifacts.yml
      parameters:
        publish:
          - key: docs
            value: '/documentation/build'