# Build shared .NET Core Application to run wihin IIS
# For the full suite please check the other pipelines
variables:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  NUGET_XMLDOC_MODE: skip
  CI: true
  npm_config_cache: $(Pipeline.Workspace)/.npm
  NUGET_PACKAGES: $(Pipeline.Workspace)/.nuget/packages

trigger:
  branches:
    include:
    - feature/auto_dotnet_sdk_version_upgrade*
    exclude:
    - release/*
  paths:
    include:
    - starsky/*
    exclude:
    - starskydesktop/*
    - starsky-tools/*
    - starsky.netframework/*
    - starsky/readme.md
    - starsky/starsky/readme.md
    - starsky/starsky/clientapp/readme.md
    - /*.md
    - /*.json
    - starsky/nuget-packages-list.json

pr:
  branches:
    exclude:
    - master

pool:
  vmImage: 'ubuntu-24.04'

steps:
- checkout: self
  clean: true
  fetchDepth: 1

- template: /pipelines/azure/steps/use_dotnet_version.yml

- template: /pipelines/azure/steps/build_clientapp.yml
  parameters:
    jest: false

- template: /pipelines/azure/steps/build_server_shared_runtime.yml
  parameters:
    nugetPackages: $(NUGET_PACKAGES)

- template: /pipelines/azure/steps/publish_end2end_container.yml

- task: PublishPipelineArtifact@1
  inputs:
    path: '$(Build.SourcesDirectory)//starsky/starsky/generic-site'
    ArtifactName: 'generic-site'
