import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';


/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

const sidebars: SidebarsConfig = {
	// By default, Docusaurus generates a sidebar from the docs folder structure
	advancedOptions: [{ type: "autogenerated", dirName: "advanced-options" }],
	features: [{ type: "autogenerated", dirName: "features" }],
	gettingStarted: [{ type: "autogenerated", dirName: "getting-started" }],
	developerGuide: [{ type: "autogenerated", dirName: "developer-guide" }],

	// But you can create a sidebar manually
	/*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
