name: Auto Client App create Vite upgrade

on:
  workflow_dispatch:
  schedule:
    - cron:  '30 4 15 * *'
    
jobs:
  run:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: master
        
    - name: Setup Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: 18
        check-latest: true
  
    - name: 'Update clientapp'
      id: clientapp_vite_app_update
      working-directory: ./starsky-tools/build-tools
      run: npm run clientapp-vite-app-update
      
    - shell: bash
      working-directory: ./starsky
      id: files_changed
      run: |
        git status
        git status --porcelain
      
        if [[ `git status --porcelain` ]]; then
          echo "There are files not committed yet"
          echo "CHANGED=true" >> $GITHUB_OUTPUT
        else 
          echo "not changed"
          echo "CHANGED=false" >> $GITHUB_OUTPUT
        fi
      
    - name: Create Pull Request ${{ steps.files_changed.outputs.CHANGED }}
      id: cpr
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.WORKFLOW_GITHUB }}
        commit-message: 'Update ClientApp'
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        signoff: false
        add-paths: |
          *
        branch: feature/auto_clientapp_vite_app_update
        delete-branch: true
        title: 'Client App - Vite - Upgrade dependencies'
        body: |
          ## Upgrade Client App to the latest version
          - todo: test!         
        labels: |
          dependencies
        draft: false
        
    - name: Merge current branch into -> auto_clientapp_vite_app_update
      uses: everlytic/branch-merge@1.1.5
      if: github.event_name == 'workflow_dispatch' && steps.files_changed.outputs.CHANGED == 'true'
      with:
        github_token: ${{ secrets.WORKFLOW_GITHUB }}
        source_ref: 'master'
        target_branch: feature/auto_clientapp_vite_app_update
        commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'
