name: Auto Update Swagger

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
    - '**.cshtml'
    - '**.cs'
    - '**.sln'
    - '**.cake'
    - '**.json'
    - '.github/workflows/auto-update-swagger-dotnet.yml'
  pull_request:
    branches: [ master ]
    paths:
    - '.github/workflows/auto-update-swagger-dotnet.yml'
    - 'documentation/static/openapi/openapi.json'

 
jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.408

    - name: Cache nuget packages (*nix)
      uses: actions/cache@v3
      with:
        # nuget cache files are stored in `~/.nuget/packages` on Linux/macOS
        path: ~/.nuget/packages
        key: ${{ runner.os }}-build-netcore-${{ hashFiles('./starsky/starsky/nuget-packages-list.json') }}
        restore-keys: |
          ${{ runner.os }}-build-netcore-

    - name: Run With Exit
      shell: bash
      working-directory: ./starsky/starsky
      env: 
        app__AddSwagger: "true"
        app__AddSwaggerExport: "true"
        app__AddSwaggerExportExitAfter: "true"
        app__SyncOnStartup: "false"
        app__thumbnailGenerationIntervalInMinutes: 0
        app__EnablePackageTelemetry: "false"
        app__useDiskWatcher: "false"
        app__GeoFilesSkipDownloadOnStartup: "true"
        app__ExiftoolSkipDownloadOnStartup: "true"
      run: dotnet run --no-launch-profile

    - name: Copy
      shell: bash
      run: cp starsky/starsky/bin/Debug/net6.0/temp/starsky.json documentation/static/openapi/openapi.json

    - name: Generate swagger
      shell: bash
      working-directory: ./documentation
      run: node scripts/openapi.js

    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        author_name: SwaggerUpdateBot
        author_email: qdraw@users.noreply.github.com
        message: "[Swagger] Auto commited swagger/openapi list"
        add: "documentation/static/openapi/openapi.json"
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        author_name: SwaggerUpdateBot
        author_email: qdraw@users.noreply.github.com
        message: "[Swagger] Auto commited swagger/openapi list"
        add: "docs/api/readme.md"
        github_token: ${{ secrets.GITHUB_TOKEN }}


