name: Auto Update Swagger

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
    - '**.cshtml'
    - '**.cs'
    - '**.sln'
    - '**.cake'
    - '**.json'
    - '.github/workflows/auto-update-swagger-dotnet.yml'
  pull_request:
    branches: [ master ]
    paths:
    - '.github/workflows/auto-update-swagger-dotnet.yml'
    - 'starsky-tools/docs/assets/config/starsky.json'

 
jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.402

    - name: Cache nuget packages (*nix)
      uses: actions/cache@v2
      with:
        # nuget cache files are stored in `~/.nuget/packages` on Linux/macOS
        path: ~/.nuget/packages
        key: ${{ runner.os }}-build-netcore-${{ hashFiles('./starsky/starsky/nuget-packages-list.json') }}
        restore-keys: |
          ${{ runner.os }}-build-netcore-
 
    - name: BuildNetCore
      shell: bash
      working-directory: ./starsky
      run: bash build.sh --Target=BuildNetCore --no-sonar --no-client --no-test --no-dependencies
     
    - name: Run With Exit
      shell: bash
      working-directory: ./starsky/starsky
      env: 
        app__AddSwagger: "true"
        app__AddSwaggerExport: "true"
        app__AddSwaggerExportExitAfter: "true"
      run: dotnet run --no-launch-profile

    - name: Copy
      shell: bash
      run: cp starsky/starsky/bin/Debug/net6.0/temp/starsky.json starsky-tools/docs/assets/config/starsky.json

    - name: Generate swagger
      shell: bash
      working-directory: ./starsky-tools/docs
      run: node swagger.js

    - name: Commit changes
      uses: EndBug/add-and-commit@v4
      with:
        author_name: DocsUpdateBot
        author_email: qdraw@users.noreply.github.com
        message: "[NugetPackagesListUpdate] Auto commited swager list"
        add: "starsky-tools/docs/assets/config/starsky.json"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



