name: Dotnet sdk version update

on:
  workflow_dispatch:
  schedule:
    - cron:  '45 0 * * *'
    
jobs:
  run:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: 'Update .NET Versions'
      id: dotnet_sdk_version_update
      working-directory: ./starsky-tools/build-tools
      run: npm run dotnet-sdk-version-update
      
    - name: Npm generate package list  ${{ steps.dotnet_sdk_version_update.outputs.SDK_VERSION }}
      working-directory: ./starsky-tools/build-tools
      run: npm run nuget-package-list
      
    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.WORKFLOW_GITHUB }}
        commit-message: '.NET Upgrade to ${{ steps.dotnet_sdk_version_update.outputs.SDK_VERSION }}'
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        signoff: false
        branch: feature/auto_dotnet_sdk_version_update_${{ steps.dotnet_sdk_version_update.outputs.SDK_VERSION }}
        delete-branch: true
        title: '.NET SDK Upgrade to ${{ steps.dotnet_sdk_version_update.outputs.SDK_VERSION }}'
        body: |
          Upgrade of .NET with newer SDK Version
          - First test on linux-arm test envs before approve
          - update azure runtime on test
          - when upgrading to newer major release check docker
          - update docs with minimal version
        labels: |
          dependencies
        draft: false

  
