on:
  workflow_dispatch:

name: End2End test

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create temp folder
        shell: bash
        id: create_temp_folder
        run: mkdir starsky-run && cd starsky-run && echo "::set-output name=folder_path::$(pwd)"

      - name: github-artifacts-download
        shell: bash
        working-directory: ./starsky/starsky
        run: bash github-artifacts-download.sh --output ${{ steps.create_temp_folder.outputs.folder_path }} --token ${{ secrets.GITHUB_TOKEN }}

      - name: pm2-new-instance
        shell: bash
        working-directory: ./starsky/starsky
        run: bash pm2-new-instance.sh --output ${{ steps.create_temp_folder.outputs.folder_path }} || true

      - name: Test service
        shell: bash
        run:  |
          cd ${{ steps.create_temp_folder.outputs.folder_path }}
          echo ${{ steps.create_temp_folder.outputs.folder_path }}
          ls
          bash service-deploy-systemd.sh
          
      - name: service-deploy-systemd
        shell: bash
        working-directory: ${{ steps.create_temp_folder.outputs.folder_path }}
        run: bash service-deploy-systemd.sh
