name: end2end on heroku-demo

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Run Cypress in Electron 
      uses: cypress-io/github-action@v1
      with:
        command: npm run e2e:heroku-demo
