name: end2end on heroku-demo

on:
  workflow_dispatch:
  #schedule:
#    - cron:  '45 0 * * *'
    
jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Run Cypress in Electron 
      uses: cypress-io/github-action@v2
      env:
        CYPRESS_BASE_URL: https://demostarsky.herokuapp.com  
        cypress_name: heroku-demo
        cypress_AUTH_USER: demo@qdraw.nl
        cypress_AUTH_PASS:  demo@qdraw.nl
        CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      with:
        command: npm run e2e:env:record -- --tag "heroku"
        working-directory: starsky-tools/end2end  

    - name: Upload screenshots (always)
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: cypress-screenshots
        path: starsky-tools/end2end/cypress/screenshots

    - name: Upload videos (always)
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: cypress-videos
        path: starsky-tools/end2end/cypress/videos 
  
