name: Docker buildx multi-arch CI unstable master

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ master ]
    paths:
    - '.github/workflows/starsky-docker-buildx.yml'
    - 'starsky/**'
    
  pull_request:
    branches: [ master ]
    paths:
    - '.github/workflows/starsky-docker-buildx.yml'
    - 'starsky/Dockerfile'
    
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    
      - name: Check Out Repo 
        uses: actions/checkout@v4
        
      - name: Log in to Github Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}        

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Inspect Docker Buildx
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"

      - name: Extract metadata Github Actions (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}

      - name: Build and push master
        id: docker_build_push
        uses: docker/build-push-action@v5
        if: github.event_name != 'pull_request'
        with:
          context: ./starsky
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: TOOLS=true
          
      - name: Build and don't push
        id: docker_build_pull_request
        uses: docker/build-push-action@v5
        if: github.event_name == 'pull_request'
        with:
          context: ./starsky
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: false
