name: Starsky Docker Deploy Demo

on:
  push:
    branches:
    - master
    - release/*
  pull_request:
    branches: [ master ]
    paths:
    - '.github/workflows/starsky-docker-deploy-demo-env.yml'
    - 'starsky/Dockerfile'
    - 'starsky/docker_demo_setup.sh'
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build and deploy the Docker image
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        APP_NAME: ${{ 'demostarsky' }}
      run: |
        cd ./starsky
        docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
        heroku container:push web -a $APP_NAME --arg ISDEMO=true 
        heroku container:release web -a $APP_NAME
        
  trigger_pipe:
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
      - name: trigger end2end-on-heroku-demo
        shell: bash
        env:
          NOTE_READ_THIS_NOW: "Need a github token that has more rights otherwise it will be ignored"
        run: |
          curl \
          -H"authorization: Bearer ${{ secrets.WORKFLOW_GITHUB }}" \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/end2end-on-heroku-demo.yml/dispatches \
          -d '{"ref":"master"}' -v

          
