on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    paths:
    - '.github/workflows/starsky-docker-buildx.yml'
    - 'starsky/Dockerfile'
    - 'starsky/docker_demo_setup.sh'
  workflow_dispatch:
  
name: Docker buildx multi-arch CI (push is false)

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Inspect Docker Buildx
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"

      - name: Build and push master
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./starsky
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: false
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/starsky:latest
