name: Nuget packages list update
on:
  push:
    branches:
      - master
      - release/*

jobs: 
  run:
    name: Update Nuget packages list
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
      
    - name: Npm generate package list
      working-directory: ./starsky-tools/build-tools
      run: npm run nuget-package-list

    - name: Commit changes
      uses: EndBug/add-and-commit@v4
      with:
        author_name: DocsUpdateBot
        author_email: qdraw@users.noreply.github.com
        message: "[NugetPackagesListUpdate] Auto commited nugetPackages list"
        add: "starsky/nuget-packages-list.json"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
