on:
  pull_request:
    branches: [ master ]
    paths:
    - 'starsky/starsky-tools/download-mirror-exiftool.sh'
    - 'starsky/starsky-tools/download-mirror-ffmpeg.sh'
    - 'starsky/starsky-tools/download-mirror-geonames.sh'
    - 'starsky/starsky-tools/download-mirror.sh'
    - '.github/workflows/tools-dependencies-mirror-netlify.yml'
  push:
    branches: [ master ]
    paths:
    - 'starsky/starsky-tools/download-mirror-exiftool.sh'
    - 'starsky/starsky-tools/download-mirror-ffmpeg.sh'
    - 'starsky/starsky-tools/download-mirror-geonames.sh'
    - 'starsky/starsky-tools/download-mirror.sh'
    - '.github/workflows/tools-dependencies-mirror-netlify.yml'    
  workflow_dispatch:
    
name: Tools dependencies mirror netlify

jobs:
  test:
    name: Mirror
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
          
      - name: download-mirror.sh
        working-directory: starsky-tools/build-tools
        run: bash download-mirror.sh

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-tools-mirror
          path: ./starsky-tools/build-tools/mirror/

      - name: ls && pwd
        shell: bash
        working-directory: ./starsky-tools/build-tools/mirror/
        run: touch index.html && ls -lah && pwd       

      - name: Install Netlify
        if: github.event_name != 'pull_request'
        run: npm install netlify-cli@17.37.2 -g
        
      - name: Deploy to Netlify
        if: github.event_name != 'pull_request'
        id: netlify_deploy
        working-directory: ./starsky-tools/build-tools/        
        run: |
          netlify deploy \
            --dir mirror \
            --site ${{ secrets.NETLIFY_MIRROR_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_AUTH_TOKEN }}
